# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
dataset_fields:

  - field_name: ds:prjTitle
    label: Project title
    datajson: ds:prjTitle

  - field_name: ds:prjURL
    label: Project URL
    datajson: ds:prjURL

  - field_name: ds:prjWebpage
    label: Project web page
    datajson: ds:prjWebpage

  - field_name: ds:prjKeywords
    label: Project keywords
    datajson: ds:prjKeywords

  - field_name: ds:prjType
    label: Project type
    datajson: ds:prjType

  - field_name: ds:prjDescription
    label: Project description
    datajson: ds:prjDescription

  - field_name: ds:prjStartDate
    label: Project start date
    datajson: ds:prjStartDate

  - field_name: ds:prjEndDate
    label: Project end date
    datajson: ds:prjEndDate

  - field_name: ds:prjFundingAgency
    label: Project funding agency
    datajson: ds:prjFundingAgency

  - field_name: ds:prjInput
    label: Project input
    datajson: ds:prjInput

  - field_name: ds:prjOutput
    label: Project output
    datajson: ds:prjOutput

  - field_name: ds:prjCoordinator
    label: Project coordinator
    datajson: ds:prjCoordinator

  - field_name: ds:prjObservations
    label: Project observations
    datajson: ds:prjObservations

  - field_name: ds:prjCoordinatorOrganization
    label: Project coordinator organization
    datajson: ds:prjCoordinatorOrganization

  - field_name: ds:prjProjectArea
    label: Project area
    datajson: ds:prjProjectArea

  - field_name: ds:prjMembers
    label: Project members
    datajson: ds:prjMembers

  - field_name: ds:prjTargetLocation
    label: Project target location
    datajson: ds:prjTargetLocation

  - field_name: ds:prjTargetPopulation
    label: Project target population
    datajson: ds:prjTargetPopulation

  - field_name: ds:prjOverallParticipantsInvolved
    label: Overall participants involved
    datajson: ds:prjOverallParticipantsInvolved

  - field_name: ds:prjSelectedParticipants
    label: Selected participants
    datajson: ds:prjSelectedParticipants

  - field_name: ds:prjTypeOfMeasurements
    label: Type of measurements
    datajson: ds:prjTypeOfMeasurements

  - field_name: ds:prjIRBApprovalDate
    label: IRB approval date
    datajson: ds:prjIRBApprovalDate

  - field_name: ds:prjIRBApprovalOrganization
    label: IRB approval organization
    datajson: ds:prjIRBApprovalOrganization

  - field_name: ds:prjIRBApprovalNumber
    label: IRB approval number
    datajson: ds:prjIRBApprovalNumber

  - field_name: ds:prjCiteAs
    label: Cite as
    datajson: ds:prjCiteAs

  - field_name: ds:prjMaintenance
    label: Maintenance
    datajson: ds:prjMaintenance

  - field_name: ds:prjLatitude
    label: Latitude
    datajson: ds:prjLatitude

  - field_name: ds:prjLongitude
    label: Longitude
    datajson: ds:prjLongitude

  - field_name: ds:prjThumbnailUrl
    label: Thumbnail URL
    datajson: ds:prjThumbnailUrl

  - field_name: ds:prjIdentifier
    label: Project Identifier
    datajson: ds:prjIdentifier

  - field_name: ds:prjDownloadRequestEmail
    label: Download request email
    datajson: ds:prjDownloadRequestEmail

#  - field_name: durationFacet
#    label: Duration facet
#    datajson: durationFacet

#  - field_name: locationFacet
#    label: Location facet
#    datajson: locationFacet

#  - field_name: collectionFacet
#    label: Collection facet
#    datajson: collectionFacet

#  - field_name: categoryFacet
#    label: Category facet
#    datajson: categoryFacet

  - field_name: ds:prjAdditionalMaterialName
    label: Additional material name
    datajson: ds:prjAdditionalMaterialName

  - field_name: ds:prjAdditionalMaterialUrl
    label: Additional material URL
    datajson: ds:prjAdditionalMaterialUrl

  - field_name: ds:prjAdditionalMaterialFormat
    label: Additional material format
    datajson: ds:prjAdditionalMaterialFormat

  - field_name: ds:prjDocumentationName
    label: Documentation name
    datajson: ds:prjDocumentationName

  - field_name: ds:prjDocumentationURL
    label: Documentation URL
    datajson: ds:prjDocumentationURL

  - field_name: ds:prjDocumentationFormat
    label: Documentation format
    datajson: ds:prjDocumentationFormat

  - field_name: ds:DatName
    label: Dataset Name
    datajson: ds:DatName

  - field_name: ds:DatDescription
    label: Dataset Description
    datajson: ds:DatDescription

#  - field_name: ds:prjTitle
#    label: Project Title
#    datajson: ds:prjTitle

  - field_name: ds:DatSensorName
    label: Sensor Name
    datajson: ds:DatSensorName

  - field_name: ds:DatType
    label: Dataset Type
    datajson: ds:DatType

  - field_name: ds:DatSensorType
    label: Sensor Type
    datajson: ds:DatSensorType
    display_template: display/sensor_type.html

  - field_name: ds:DatStartDate
    label: Data Collection Start Date
    datajson: ds:DatStartDate

  - field_name: ds:DatEndDate
    label: Data Collection End Date
    datajson: ds:DatEndDate

  - field_name: ds:DatVersion
    label: Dataset Version
    datajson: ds:DatVersion

  - field_name: ds:DatPublicationTimestamp
    label: Publication Date
    datajson: ds:DatPublicationTimestamp

  - field_name: ds:DatLicense
    label: Dataset License
    datajson: ds:DatLicense

  - field_name: ds:DatURL
    label: Dataset URL
    datajson: ds:DatURL

  - field_name: ds:DatKeyword
    label: Keywords
    datajson: ds:DatKeyword

  - field_name: ds:DatPublisher
    label: Publisher
    datajson: ds:DatPublisher

  - field_name: ds:DatCreator
    label: Creator
    datajson: ds:DatCreator

  - field_name: ds:DatOwner
    label: Owner Email
    datajson: ds:DatOwner

  - field_name: ds:DatLanguage
    label: Language
    datajson: ds:DatLanguage

  - field_name: ds:DatLevel
    label: Dataset Level
    datajson: ds:DatLevel

  - field_name: ds:DatSize
    label: Dataset Size
    datajson: ds:DatSize

  - field_name: ds:DatDomain
    label: Domain
    datajson: ds:DatDomain

  - field_name: ds:DatFileFormat
    label: File Format
    datajson: ds:DatFileFormat

  - field_name: ds:DatDetailedDescription
    label: Detailed Description
    datajson: ds:DatDetailedDescription

  - field_name: ds:DatDownloadRequest
    label: Download Request
    datajson: ds:DatDownloadRequest

  - field_name: ds:DatConditionsOfAccess
    label: Conditions of Access
    datajson: ds:DatConditionsOfAccess

  - field_name: ds:DatGenre
    label: Genre
    datajson: ds:DatGenre

  - field_name: ds:DatisAccessibleForFree
    label: Accessible for Free
    datajson: ds:DatisAccessibleForFree

  - field_name: ds:DatExpires
    label: Expiration Date
    datajson: ds:DatExpires



  - field_name: ds:DatFiveStars
    label: 5-Star Rating
    datajson: ds:DatFiveStars

  - field_name: ds:DatOrigin
    label: Data Origin
    datajson: ds:DatOrigin

  - field_name: ds:DatCreativeWorkStatus
    label: Creative Work Status
    datajson: ds:DatCreativeWorkStatus

  - field_name: ds:DatDownloadRequestName
    label: Download Request Name
    datajson: ds:DatDownloadRequestName

  - field_name: ds:DatDownloadRequestURL
    label: Download Request URL
    datajson: ds:DatDownloadRequestURL

  - field_name: ds:DatDownloadRequestFormat
    label: Download Request Format
    datajson: ds:DatDownloadRequestFormat

  - field_name: ds:DatCodebookName
    label: Codebook Name
    datajson: ds:DatCodebookName

  - field_name: ds:DatCodebookURL
    label: Codebook URL
    datajson: ds:DatCodebookURL

  - field_name: ds:DatCodebookFormat
    label: Codebook Format
    datajson: ds:DatCodebookFormat

  - field_name: ds:DatIdentifier
    label: Dataset Identifier
    datajson: ds:DatIdentifier

  - field_name: ds:DatChangelogURL
    label: Changelog URL
    datajson: ds:DatChangelogURL

  - field_name: ds:DatLicenceURL
    label: License URL
    datajson: ds:DatLicenceURL

  - field_name: ds:DatSha256
    label: SHA-256 Hash
    datajson: ds:DatSha256

  - field_name: ds:DatUpdateTimestamp
    label: Update Timestamp
    datajson: ds:DatUpdateTimestamp

  - field_name: ds:DatBasedOn
    label: Based On
    datajson: ds:DatBasedOn


#  - field_name: dDurationFacet
#    label: Duration Facet
#    datajson: datDurationFacet

#  - field_name: locationFacet
#    label: Location Facet
#    datajson: locationFacet

#  - field_name: dataTypeFacet
#    label: Data Type Facet
#    datajson: dataTypeFacet

#  - field_name: categoryFacet
#    label: Category
#    datajson: categoryFacet



resource_fields:
  - field_name: name
    label: Resource Name
    datajson: distribution.title
  - field_name: url
    label: URL
    datajson: distribution.downloadURL
  - field_name: format
    label: Format
    datajson: distribution.format
    form_template: form/dropdown.html
    values:
      - api
      - csv
      - rdf
      - json
      - geojson
      - html
      - kml
      - kmz
      - shp
      - xml
      - pdf

organization_fields:
  - field_name: title
    label: Title
  - field_name: description
    label: Description
  - field_name: logo
    label: Logo

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html
